export default defineAppConfig({
  ui: {
    colors: {
      primary: 'cyan',
      neutral: 'zinc',
      success: 'green',
      warning: 'orange',
      error: 'red',
      info: 'purple',
    },
    icons: {
      arrowDown: 'i-mdi-arrow-down',
      arrowLeft: 'i-mdi-arrow-left',
      arrowRight: 'i-mdi-arrow-right',
      arrowUp: 'i-mdi-arrow-up',
      caution: 'i-mdi-alert-box',
      check: 'i-mdi-check',
      chevronDoubleLeft: 'i-mdi-chevron-double-left',
      chevronDoubleRight: 'i-mdi-chevron-double-right',
      chevronDown: 'i-mdi-chevron-down',
      chevronLeft: 'i-mdi-chevron-left',
      chevronRight: 'i-mdi-chevron-right',
      chevronUp: 'i-mdi-chevron-up',
      close: 'i-mdi-close',
      copy: 'i-mdi-content-copy',
      copyCheck: 'i-mdi-clipboard-check',
      dark: 'i-mdi-weather-night',
      drag: 'i-mdi-drag-vertical',
      ellipsis: 'i-mdi-dots-horizontal',
      error: 'i-mdi-close-box',
      external: 'i-mdi-open-in-new',
      eye: 'i-mdi-eye',
      eyeOff: 'i-mdi-eye-off',
      file: 'i-mdi-file',
      folder: 'i-mdi-folder',
      folderOpen: 'i-mdi-folder-open',
      hash: 'i-mdi-pound',
      info: 'i-mdi-information-box',
      light: 'i-mdi-white-balance-sunny',
      loading: 'i-mdi-loading',
      menu: 'i-mdi-menu',
      minus: 'i-mdi-minus',
      panelClose: 'i-mdi-arrow-collapse-left',
      panelOpen: 'i-mdi-arrow-expand-right',
      plus: 'i-mdi-plus',
      reload: 'i-mdi-reload',
      search: 'i-mdi-magnify',
      stop: 'i-mdi-stop',
      star: 'i-mdi-star',
      success: 'i-mdi-check-box',
      system: 'i-mdi-monitor',
      tip: 'i-mdi-lightbulb-on',
      upload: 'i-mdi-upload',
      warning: 'i-mdi-alert',
    },
  },
})
